---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The harp at Nature’s advent strung  
Has never ceased to play;  
The song the stars of morning sung  
Has never died away.  

And prayer is made, and praise is given,  
By all things near and far;  
The ocean looketh up to heaven,  
And mirrors every star.  

Its waves are kneeling on the strand,  
As kneels the human knee,  
Their white locks bowing to the sand,  
The priesthood of the sea!  

They pour their glittering treasures forth,  
Their gifts of pearl they bring,  
And all the listening hills of earth  
Take up the song they sing.  

The green earth sends its incense up  
From many a mountain shrine;  
From folded leaf and dewy cup  
She pours her sacred wine.  